# Generated by Django 5.1.2 on 2024-11-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/')),
                ('id_animal', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1)),
                ('madre_id', models.CharField(blank=True, max_length=10)),
                ('padre_id', models.CharField(blank=True, max_length=10)),
                ('raza_principal', models.CharField(choices=[('Simmental', 'Simmental'), ('Brahman', 'Brahman'), ('Jersey', 'Jersey'), ('Nelore', 'Nelore'), ('Angus', 'Angus'), ('Hereford', 'Hereford'), ('Holstein', 'Holstein'), ('Charolais', 'Charolais'), ('Otro', 'Otro')], max_length=50)),
                ('raza_secundaria', models.CharField(blank=True, choices=[('Simmental', 'Simmental'), ('Brahman', 'Brahman'), ('Jersey', 'Jersey'), ('Nelore', 'Nelore'), ('Angus', 'Angus'), ('Hereford', 'Hereford'), ('Holstein', 'Holstein'), ('Charolais', 'Charolais'), ('Otro', 'Otro')], max_length=50)),
                ('raza_terciaria', models.CharField(blank=True, choices=[('Simmental', 'Simmental'), ('Brahman', 'Brahman'), ('Jersey', 'Jersey'), ('Nelore', 'Nelore'), ('Angus', 'Angus'), ('Hereford', 'Hereford'), ('Holstein', 'Holstein'), ('Charolais', 'Charolais'), ('Otro', 'Otro')], max_length=50)),
                ('rasgos_especiales', models.TextField(blank=True)),
                ('categoria', models.CharField(choices=[('Destace', 'Destace'), ('Exportación', 'Exportación'), ('Producción de Leche', 'Producción de Leche'), ('Producción de Carne', 'Producción de Carne'), ('Producción de Reproducción', 'Producción de Reproducción'), ('Venta', 'Venta')], max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('ultimo_parto', models.DateField(blank=True, null=True)),
                ('fecha_preñez', models.DateField(blank=True, null=True)),
                ('fecha_ultimo_celo', models.DateField(blank=True, null=True)),
                ('dias_preñez', models.IntegerField(blank=True, null=True)),
                ('fecha_esperada_parto', models.DateField(blank=True, null=True)),
                ('produccion_diaria_leche', models.FloatField(blank=True, null=True)),
                ('dias_lactancia', models.IntegerField(blank=True, null=True)),
                ('control_lacteo', models.BooleanField(default=False)),
                ('estado_salud', models.TextField(blank=True)),
                ('vacunacion_brucelosis', models.BooleanField(default=False)),
                ('otras_vacunas', models.TextField(blank=True)),
                ('peso_actual', models.FloatField()),
                ('edad', models.CharField(max_length=20)),
                ('entrada_hato', models.DateField(blank=True, null=True)),
                ('iep', models.CharField(blank=True, max_length=20)),
                ('iy', models.IntegerField(blank=True, null=True)),
                ('u', models.FloatField(blank=True, null=True)),
                ('para_venta', models.BooleanField(default=False)),
                ('precio_estimado', models.FloatField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True)),
            ],
        ),
    ]
