# Generated by Django 5.1.2 on 2024-11-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_animal_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='id_animal',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='madre_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='animal',
            name='padre_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
