# Generated by Django 5.1.2 on 2024-11-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_animal_id_animal_alter_animal_madre_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='draft',
            field=models.BooleanField(default=True),
        ),
    ]
